export const Package = [
  {
    title: "Basic",
    description: "the production company charges a fixed",
    price: "$1,200",
    perproject: "/per project",
    button: "select plan",
    include: "Includes:",
    items1: "Pre-production",
    items2: "Production",
    items3: "Post-production",
    items4: "Crew Members",
    items5: "Equipment",
    items6: "Delivery Time",
    items7: "Revisions",
  },
  {
    title: "Pro",
    description: "the production company charges a fixed",
    price: "$5,000",
    perproject: "/per project",
    button: "select plan",
    include: "Includes:",
    items1: "Pre-production",
    items2: "Production",
    items3: "Post-production",
    items4: "Crew Members",
    items5: "Equipment",
    items6: "Delivery Time",
    items7: "Revisions",
  },
  {
    title: "Enterprise",
    description: "the production company charges a fixed",
    price: "Custom Quote",
    button: "custom quote",
    include: "Includes:",
    items1: "Pre-production",
    items2: "Production",
    items3: "Post-production",
    items4: "Crew Members",
    items5: "Equipment",
    items6: "Delivery Time",
    items7: "Revisions",
  },
];
