export const PortfoliocardsData = [
  {
    id: 1,
    src: "assets/img/workimg.jpg",
    title: "TV Commecial",
    description: "Proin et magna blandit arcu pellentes sceleris ameta.",
    para: "2023",
  },
  {
    id: 2,
    src: "assets/img/workcamera.jpg",
    title: "Indie Movie",
    description: "Proin et magna blandit arcu pellentes sceleris ameta..",
    para: "2023",
  },
  {
    id: 3,
    src: "assets/img/film2.jpg",
    title: "Documentary",
    description: "Proin et magna blandit arcu pellentes sceleris ameta.",
    para: "2023",
  },
  {
    id: 4,
    src: "assets/img/guiter.jpg",
    title: "Company Profile",
    description: "Proin et magna blandit arcu pellentes sceleris ameta.",
    para: "2023",
  },
  {
    id: 5,
    src: "assets/img/userimg2.jpg",
    title: "Company Profile",
    description: "Proin et magna blandit arcu pellentes sceleris ameta.",
    para: "2023",
  },
  {
    id: 6,
    src: "assets/img/userimg1.jpg",
    title: "Company Profile",
    description: "Proin et magna blandit arcu pellentes sceleris ameta.",
    para: "2023",
  },
  {
    id: 7,
    src: "assets/img/coffee.jpg",
    title: "Company Profile",
    description: "Proin et magna blandit arcu pellentes sceleris ameta.",
    para: "2023",
  },
  {
    id: 8,
    src: "assets/img/cutecat.jpg",
    title: "Company Profile",
    description: "Proin et magna blandit arcu pellentes sceleris ameta.",
    para: "2023",
  },
  {
    id: 9,
    src: "assets/img/popcorn.jpg",
    title: "Company Profile",
    description: "Proin et magna blandit arcu pellentes sceleris ameta.",
    para: "2023",
  },
  {
    id: 10,
    src: "assets/img/hall.jpg",
    title: "Company Profile",
    description: "Proin et magna blandit arcu pellentes sceleris ameta.",
    para: "2023",
  },
  {
    id: 11,
    src: "assets/img/film2.jpg",
    title: "Documentary",
    description: "Proin et magna blandit arcu pellentes sceleris ameta.",
    para: "2023",
  },
  {
    id: 12,
    src: "assets/img/guiter.jpg",
    title: "Company Profile",
    description: "Proin et magna blandit arcu pellentes sceleris ameta.",
    para: "2023",
  },
];
